### ISSUE TITLE
Numbers are missing in teams tab

### ISSUE THREAD

**Issue by Zhurik** [catppuccin/mattermost#1]
In tab where teams are shown numbers in the corner of icon are not shown. I cannot figure out if this intended or just some kind of a bug. I can fix it but I don't know what color to pick for each theme. Screenshot below:

<img width="48" alt="image" src="https://github.com/catppuccin/mattermost/assets/20578586/c0bd7b00-fee8-4dc6-b202-109c030144ed">

Theme: Frappe
OS: MacOS

**Comment by nekowinston** [comment]
Hey, thanks for the issue
This definitely wasn't intended - I've pushed a fix using `crust` as the foreground color for the mentions.
